### ISSUE TITLE
is it really necessary to "upload" everything to poggit?

### ISSUE THREAD

**Issue by T14Raptor** [PedsHamptonDevs/EnchantmentInfoUI#1]
also stop making new accounts and yes ik this is an organization and not an account

**Comment by T14Raptor** [comment]
wow then u leave the organization .-.

**Comment by Zadezter** [comment]
What is going on?

**Comment by T14Raptor** [comment]
This guy makes the most useless UI’s ever, and he just "uploads" them to poggit, and then it just spams the discord channel out. It’s actually the most useless UI’s, stuff like a "FlyUI".
